const DUMMY_FOOD_DATA = [
  {
    id: 1,
    name: "Двойной чизбургер",
    category: "burger",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/burger1.png",
    price: 29,
    desc: "Попробуйте сегодня наше вкусное бургерное меню и насладитесь сытным ужином.",
  },
  {
    id: 2,
    name: "Шоколадные пончики",
    category: "desert",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/desert1.png",
    price: 9.0,
    desc: "The Donut Shack Побалует своих сладкоежек нашим соблазнительным десертным меню, тортами, пирогами, мороженым, пудингами и многим другим.",
  },
  {
    id: 3,
    name: "Рыбный салат",
    category: "meal",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/meal1.png",
    price: 34.0,
    desc: "Насладитесь сытными и сбалансированными блюдами в нашем меню, включающем широкий выбор блюд различных кухонь и культур.",
  },
  {
    id: 4,
    name: "Пицца с креветками",
    category: "pizza",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/pizza1.png",
    price: 24.0,
    desc: "Ощутите подлинный вкус Италии с нашей пиццей из меню со свежими и сырными начинками.",
  },
  {
    id: 5,
    name: "Сырный бургер",
    category: "burger",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/burger2.png",
    price: 19.0,
    desc: "Попробуйте сегодня наше вкусное бургерное меню и насладитесь сытным ужином.",
  },
  {
    id: 6,
    name: "Закусочная с пончиками",
    category: "desert",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/desert2.png",
    price: 14.0,
    desc: "Побалуйте своих сладкоежек нашим соблазнительным десертным меню, тортами, пирогами, мороженым, пудингами и многим другим.",
  },
  {
    id: 7,
    name: "Салат из курицы",
    category: "meal",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/meal2.png",
    price: 25.0,
    desc: "Насладитесь сытными и сбалансированными блюдами в нашем меню, включающем широкий выбор блюд различных кухонь и культур.",
  },
  {
    id: 8,
    name: "Тайская пицца с курицей",
    category: "pizza",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/pizza2.png",
    price: 35.0,
    desc: "Ощутите подлинный вкус Италии с нашей пиццей из меню со свежими и сырными начинками.",
  },
  {
    id: 9,
    name: "Овощной чизбургер",
    category: "burger",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/burger3.png",
    price: 35.0,
    desc: "Попробуйте сегодня наше вкусное бургерное меню и насладитесь сытным ужином.",
  },
  {
    id: 10,
    name: "Красный бархат",
    category: "desert",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/desert3.png",
    price: 15.0,
    desc: "Побалуйте своих сладкоежек нашим соблазнительным десертным меню, тортами, пирогами, мороженым, пудингами и многим другим.",
  },
  {
    id: 11,
    name: "Салат Панир",
    category: "meal",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/meal3.png",
    price: 20.0,
    desc: "Насладитесь сытными и сбалансированными блюдами в нашем меню, включающем широкий выбор блюд различных кухонь и культур.",
  },
  {
    id: 12,
    name: "Смесь креветок с помидорами",
    category: "pizza",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/pizza3.png",
    price: 30.0,
    desc: "Ощутите подлинный вкус Италии с нашей пиццей из меню со свежими и сырными начинками.",
  },
  {
    id: 13,
    name: "Хрустящий бургер Панир",
    category: "burger",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/burger4.png",
    price: 35.0,
    desc: "Попробуйте сегодня наше вкусное бургерное меню и насладитесь сытным ужином.",
  },
  {
    id: 14,
    name: "Жареный чизкейк",
    category: "desert",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/desert4.png",
    price: 20.0,
    desc: "Побалуйте своих сладкоежек нашим соблазнительным десертным меню, тортами, пирогами, мороженым, пудингами и многим другим.",
  },
  {
    id: 15,
    name: "Салат из лосося",
    category: "meal",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/meal4.png",
    price: 40.0,
    desc: "Насладитесь сытными и сбалансированными блюдами в нашем меню, включающем широкий выбор блюд различных кухонь и культур.",
  },
  {
    id: 16,
    name: "Райская моцарелла",
    category: "pizza",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/pizza4.png",
    price: 45.0,
    desc: "Ощутите подлинный вкус Италии с нашей пиццей из меню со свежими и сырными начинками.",
  },
  {
    id: 17,
    name: "Бургер с тройной котлетой",
    category: "burger",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/burger5.png",
    price: 55.0,
    desc: "Попробуйте сегодня наше вкусное бургерное меню и насладитесь сытным ужином.",
  },
  {
    id: 18,
    name: "Мини-сэндвич с кремом",
    category: "desert",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/desert5.png",
    price: 10.0,
    desc: "Побалуйте своих сладкоежек нашим соблазнительным десертным меню, тортами, пирогами, мороженым, пудингами и многим другим.",
  },
  {
    id: 19,
    name: "Рис с лососем, приправленный специями",
    category: "meal",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/meal5.png",
    price: 17.0,
    desc: "Насладитесь сытными и сбалансированными блюдами в нашем меню, включающем широкий выбор блюд различных кухонь и культур.",
  },
  {
    id: 20,
    name: "Итальянский сыр",
    category: "pizza",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/pizza5.png",
    price: 23.0,
    desc: "Ощутите подлинный вкус Италии с нашей пиццей из меню со свежими и сырными начинками.",
  },
  {
    id: 21,
    name: "Макароны",
    category: "meal",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/meal6.png",
    price: 20.0,
    desc: "Насладитесь сытными и сбалансированными блюдами в нашем меню, включающем широкий выбор блюд различных кухонь и культур.",
  },
  {
    id: 22,
    name: "Классическая пицца",
    category: "pizza",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/pizza6.png",
    price: 20.0,
    desc: "Ощутите подлинный вкус Италии с нашей пиццей из меню со свежими и сырными начинками.",
  },
  {
    id: 23,
    name: "Цветущий печеный картофель",
    category: "meal",
    imgSrc: "https://raw.githubusercontent.com/rohhan36/food-app-assests/main/assets/meal7.png",
    price: 30.0,
    desc: "Насладитесь сытными и сбалансированными блюдами в нашем меню, включающем широкий выбор блюд различных кухонь и культур.",
  },
];

export default DUMMY_FOOD_DATA;
